---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: remotesecret
      path: /mutate-appstudio-redhat-com-v1beta1-remotesecret
  failurePolicy: Fail
  name: mremotesecret.kb.io
  rules:
  - apiGroups:
    - appstudio.redhat.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - remotesecrets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: remotesecret
        path: /validate-appstudio-redhat-com-v1beta1-remotesecret
    failurePolicy: Fail
    name: vremotesecret.kb.io
    rules:
      - apiGroups:
          - appstudio.redhat.com
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - remotesecrets
    sideEffects: None
