
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: secret-operator
    app.kubernetes.io/part-of: secret-operator
    app.kubernetes.io/managed-by: kustomize
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-server-cert
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
