kubernetes:
  # with this, the store is able to pull only from `default` namespace
  remoteNamespace: default
  server:
    caProvider:
      type: ConfigMap
      name: kube-root-ca.crt
      key: ca.crt
  auth:
    serviceAccount:
      name: "my-store"