apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: rs-with-overrides
  namespace: default
spec:
  secret:
    generateName: secret-
    type: kubernetes.io/basic-auth
  targets:
    - namespace: default
      secret:
        labels:
          k1: v1
          k2: v2
        name: rs-with-overrides-labels
    - namespace: default
      secret:
        annotations:
          k1: v1
          k2: v2
        name: rs-with-overrides-annos
stringData:
  username: john.doe
  password: let_me_pass
