# this can be used to delete some keys from the data for the test-remote-secret defined in
# the remote-secret.yaml.
# Applying this secret to the cluster will NOT create a new RemoteSecret 
# object, it can only associate data with a pre-existing one.
apiVersion: v1
kind: Secret
metadata:
  name: test-remote-secret-secret
  labels:
    appstudio.redhat.com/upload-secret: remotesecret
  annotations:
    appstudio.redhat.com/remotesecret-name: test-remote-secret
    appstudio.redhat.com/remotesecret-partial-update: true
    appstudio.redhat.com/remotesecret-deleted-keys: a,c,e
type: Opaque
stringData:
  # in addition to deleting some keys from the data using the above annotation, we can also perform
  # updates and additions the to keys in the same upload secret
  g: i
  j: k
