apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: test-remote-secret
  namespace: default
spec:
  secret:
    generateName: secret-from-remote-
    linkedTo:
    - serviceAccount:  
        managed:
          generateName: sa-from-remote-
  targets:
  - namespace: default 

