apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: myrs1
  namespace: default
spec:
  secret:
    generateName: secret-from-remote-
data:
  username: Z2VuYQ==
  password: Z2VuYQ==
