# this can be used to upload the data for the test-remote-secret defined in
# the remote-secret.yaml.
# Applying this secret to the cluster will NOT create a new RemoteSecret 
# object, it can only associate data with a pre-existing one.
apiVersion: v1
kind: Secret
metadata:
  name: test-remote-cluster-secret-secret
  labels:
    appstudio.redhat.com/upload-secret: remotesecret
  annotations:
    appstudio.redhat.com/remotesecret-name: test-remote-cluster-secret
type: Opaque
stringData:
  a: b
  c: d

