apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: myoriginalrs
  namespace: default
spec:
  secret:
    generateName: orig-
data:
  username: Z2VuYQ==
  password: Z2VuYQ==
---
apiVersion: v1
kind: Namespace
metadata:
  name: target-namespace
---
apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: myrs1
  namespace: target-namespace
spec:
  secret:
    generateName: copied-
dataFrom:
  name: myoriginalrs
  namespace: default
