kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: grafana-operator-system

resources:
  - ../base


generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
  - name: grafana-dashboard-prometheus-2-0-overview
    files:
      - grafana-dashboards/prometheus-2-0-overview_rev1.json
  - name: grafana-dashboard-controller-runtime
    files:
      - grafana-dashboards/controller-runtime-controllers-detail_rev1.json
  - name: grafana-dashboard-go-processes
    files:
      - grafana-dashboards/go-processes_rev1.json
