kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: grafana-operator-system


generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
  - name: grafana-dashboard-remotesecret-metrics
    files:
      - grafana-dashboards/remotesecret-metrics.json
