{
 "title": "Remote Secret General Metrics",
 "description": "Remote Secret metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Generic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failed RS data uploads",
   "type": "timeseries",
   "description": "Number of failed data upload attempts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redhat_appstudio_remotesecret_data_upload_rejected_total{operation=\"webhook_validate\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "redhat_appstudio_remotesecret_data_upload_rejected_total{operation=\"secret_data_upload\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "redhat_appstudio_remotesecret_data_upload_rejected_total{operation=\"webhook_data_upload\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "redhat_appstudio_remotesecret_data_upload_rejected_total{operation=\"copy_data_from\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Store Time Buckets",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_remotesecret_secret_store_operation_time_seconds_bucket{operation=\"store\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Time Buckets",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_remotesecret_secret_store_operation_time_seconds_bucket{operation=\"get\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Delete Time Buckets",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_remotesecret_secret_store_operation_time_seconds_bucket{operation=\"delete\"}[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}