name: "Security Scan"

on:
  push:
  schedule:
    - cron: '0 0 * * 0' # every Sunday 00:00 UTC

jobs:
  gosec:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    # Skip any created PR or push by dependabot to avoid permission issues
    if: github.actor != 'dependabot[bot]'
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-no-fail -fmt sarif -out results.sarif ./...'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
