apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-reader
  annotations:
    kubernetes.io/service-account.name: metrics-reader
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-remote-secret-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-reader
subjects:
  - kind: ServiceAccount
    name: metrics-reader
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: remote-secret-metrics-monitor
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenSecret:
        name: "metrics-reader"
        key: token
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - remotesecret
  selector:
    matchLabels:
      app.kubernetes.io/part-of: remote-secret
